-- โครงตารางทั้งหมดของระบบส่งแผนการสอน (Postgres) แปลงจาก migrate() + addColumn() ใน src/db.js รุ่น SQLite เป็นรูปสุดท้ายรูปเดียว
-- รันได้ทั้ง PGlite (ทดสอบและในเครื่อง) และ Supabase (SQL Editor) · แก้โครงตารางภายหลังให้เพิ่มไฟล์ใน db/migrations/
-- ข้อความทุกคอลัมน์ collate "C" เรียงแบบไบต์เหมือน SQLite · เวลาเป็นข้อความ YYYY-MM-DD HH:MM:SS เวลาไทย · ธง 0/1 เป็น integer
-- "current_role" เป็นคำสงวนของ Postgres ต้องครอบเครื่องหมายคำพูดทุกที่ใน SQL

create extension if not exists pgcrypto;

create table if not exists schema_version (
  version integer not null
);

create table if not exists settings (
  key text collate "C" primary key,
  value text collate "C"
);

create table if not exists departments (
  id integer generated by default as identity primary key,
  name text collate "C" not null unique,
  sort integer not null default 0
);

create table if not exists users (
  id integer generated by default as identity primary key,
  username text collate "C" not null,
  password_hash text collate "C" not null,
  must_change_password integer not null default 0,
  full_name text collate "C" not null,
  position text collate "C" not null default '',
  department_id integer references departments(id) on delete set null,
  is_teacher integer not null default 1,
  is_admin integer not null default 0,
  is_active integer not null default 1,
  signature text collate "C",
  created_at text collate "C" not null,
  last_login_at text collate "C",
  plan_quota integer not null default 1
);
-- ชื่อผู้ใช้ไม่สนตัวพิมพ์ (เดิม COLLATE NOCASE) ค้นด้วย lower(username) = lower(?)
create unique index if not exists users_username_lower on users (lower(username));

create table if not exists user_roles (
  user_id integer not null references users(id) on delete cascade,
  role text collate "C" not null,
  primary key (user_id, role)
);

create table if not exists workflow_steps (
  role text collate "C" primary key,
  seq integer not null,
  label text collate "C" not null,
  scope text collate "C" not null default 'school',
  for_manual integer not null default 1,
  for_plan integer not null default 1,
  for_note integer not null default 1
);

create table if not exists rubric_items (
  id integer generated by default as identity primary key,
  doc_type text collate "C" not null,
  seq integer not null default 0,
  title text collate "C" not null,
  max_score integer not null default 5,
  is_active integer not null default 1
);

create table if not exists subjects (
  code text collate "C" primary key,
  name text collate "C" not null,
  department_id integer references departments(id) on delete set null,
  grade text collate "C" not null default ''
);

create table if not exists submissions (
  id integer generated by default as identity primary key,
  doc_type text collate "C" not null,
  parent_id integer references submissions(id) on delete cascade,
  teacher_id integer not null references users(id),
  department_id integer references departments(id) on delete set null,
  academic_year integer not null,
  semester integer not null,
  subject_code text collate "C" not null default '',
  subject_name text collate "C" not null default '',
  grade_level text collate "C" not null default '',
  teaching_methods text collate "C" not null default '[]',
  link_url text collate "C" not null default '',
  doc_no text collate "C" not null default '',
  plan_no text collate "C" not null default '',
  topic text collate "C" not null default '',
  unit_no text collate "C" not null default '',
  unit_name text collate "C" not null default '',
  hours text collate "C" not null default '',
  class_room text collate "C" not null default '',
  teach_date text collate "C" not null default '',
  result_k text collate "C" not null default '',
  result_p text collate "C" not null default '',
  result_a text collate "C" not null default '',
  problems text collate "C" not null default '',
  suggestions text collate "C" not null default '',
  students_total integer,
  students_passed integer,
  status text collate "C" not null default 'draft',
  "current_role" text collate "C",
  returned_role text collate "C",
  score_total double precision,
  score_max double precision,
  score_detail text collate "C",
  score_role text collate "C",
  teacher_signature text collate "C",
  created_at text collate "C" not null,
  submitted_at text collate "C",
  updated_at text collate "C" not null,
  completed_at text collate "C",
  note_mode text collate "C" not null default 'type',
  -- รหัสสุ่มสำหรับ QR Code ตรวจสอบเอกสาร ตัวอักษร 0 ถึง 9 a ถึง f 20 ตัว เดาไม่ได้ และไม่เรียงตามลำดับงาน
  verify_code text collate "C" not null unique default substr(replace(gen_random_uuid()::text, '-', ''), 1, 20)
);
create index if not exists idx_sub_teacher on submissions (teacher_id);
create index if not exists idx_sub_status on submissions (status, "current_role");
create index if not exists idx_sub_term on submissions (academic_year, semester);
create index if not exists idx_sub_parent on submissions (parent_id);

create table if not exists files (
  id integer generated by default as identity primary key,
  submission_id integer not null references submissions(id) on delete cascade,
  kind text collate "C" not null,
  original_name text collate "C" not null,
  stored_name text collate "C" not null,
  mime text collate "C" not null default '',
  size integer not null default 0,
  is_current integer not null default 1,
  uploaded_at text collate "C" not null
);
create index if not exists idx_files_sub on files (submission_id);

create table if not exists reviews (
  id integer generated by default as identity primary key,
  submission_id integer not null references submissions(id) on delete cascade,
  role text collate "C",
  step_label text collate "C" not null default '',
  user_id integer references users(id) on delete set null,
  user_name text collate "C" not null default '',
  user_position text collate "C" not null default '',
  action text collate "C" not null,
  comment text collate "C" not null default '',
  score_total double precision,
  score_max double precision,
  score_detail text collate "C",
  signature text collate "C",
  created_at text collate "C" not null
);
create index if not exists idx_reviews_sub on reviews (submission_id);

create table if not exists notifications (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  from_user_id integer references users(id) on delete set null,
  from_name text collate "C" not null default '',
  text text collate "C" not null,
  link text collate "C" not null default '',
  created_at text collate "C" not null,
  read_at text collate "C"
);
create index if not exists idx_notif_user on notifications (user_id, read_at);

-- ประวัติการเปิดปิดฟังก์ชันและการตั้งค่าสำคัญ เพิ่มได้อย่างเดียว แก้ไข ลบ หรือล้างตารางไม่ได้
create table if not exists audit_log (
  id integer generated by default as identity primary key,
  at text collate "C" not null,
  user_id integer,
  user_name text collate "C" not null default '',
  action text collate "C" not null,
  detail text collate "C" not null default ''
);
create or replace function audit_log_append_only() returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception 'audit_log is append-only';
end;
$$;
drop trigger if exists audit_log_no_update on audit_log;
create trigger audit_log_no_update before update on audit_log for each row execute function audit_log_append_only();
drop trigger if exists audit_log_no_delete on audit_log;
create trigger audit_log_no_delete before delete on audit_log for each row execute function audit_log_append_only();
drop trigger if exists audit_log_no_truncate on audit_log;
create trigger audit_log_no_truncate before truncate on audit_log for each statement execute function audit_log_append_only();

-- รายวิชาที่ครูสอนในแต่ละภาค ใช้เช็กว่าส่งคู่มือครบทุกวิชา และวิชาหลักที่ต้องส่งแผน
create table if not exists teach_subjects (
  id integer generated by default as identity primary key,
  teacher_id integer not null references users(id) on delete cascade,
  academic_year integer not null,
  semester integer not null,
  subject_code text collate "C" not null,
  subject_name text collate "C" not null default '',
  grade_level text collate "C" not null default '',
  is_main integer not null default 0,
  unique (teacher_id, academic_year, semester, subject_code)
);

-- ตัวกันเดารหัสผ่าน (ตอน 12) เก็บในฐานเพราะ Workers ไม่มีหน่วยความจำค้างระหว่างคำขอ
create table if not exists login_attempts (
  key text collate "C" primary key,
  first_at bigint not null,
  count integer not null
);

-- ไฟล์ที่กำลังอัปโหลดเป็นท่อน (ตอน 10) เบราว์เซอร์ถือแค่ token ที่อยู่ปลายทาง (session_uri) อยู่ในฐานเท่านั้น
-- status: uploading = กำลังส่งท่อน · sending = มีท่อนกำลังส่งอยู่ · done = ครบแล้ว รอบันทึกงาน · used = ผูกกับงานแล้ว · trashed = ทิ้งแล้ว
-- drive_file_id = ที่เก็บไฟล์เมื่อครบ (gdrive:<id> หรือ local:<path>) รูปเดียวกับ files.stored_name
create table if not exists pending_uploads (
  token text collate "C" primary key,
  user_id integer not null references users(id) on delete cascade,
  session_uri text collate "C" not null,
  name text collate "C" not null,
  mime text collate "C" not null default '',
  size bigint not null,
  received bigint not null default 0,
  drive_file_id text collate "C",
  status text collate "C" not null default 'uploading',
  created_at text collate "C" not null
);
create index if not exists idx_pending_status on pending_uploads (status, created_at);

-- id ของโฟลเดอร์ใน Google Drive ตามตำแหน่ง เช่น ระบบส่งแผนการสอน/ภาคเรียน 2-2569 ไม่ต้องค้นใน Drive ซ้ำทุกครั้ง
create table if not exists drive_folders (
  path text collate "C" primary key,
  folder_id text collate "C" not null
);

-- เลขแผนที่ครูพิมพ์ (ยาวได้ 20 ตัว อาจว่าง หรือมีตัวอักษร) เป็นจำนวนเต็ม ใช้แทน CAST(plan_no AS INTEGER) ของ SQLite
-- อ่านเฉพาะตัวเลขต้นข้อความไม่เกิน 9 หลัก กัน integer ล้น ไม่มีตัวเลขได้ 0
-- search_path ว่าง: ใช้แต่ฟังก์ชันใน pg_catalog (คำเตือนของ Supabase ตอน 14)
create or replace function to_int_lenient(t text) returns integer language sql immutable set search_path = '' as $$
  select coalesce(nullif(substring(t from '^\s*([0-9]{1,9})'), '')::integer, 0)
$$;

insert into schema_version (version) select 1 where not exists (select 1 from schema_version);
